### ISSUE TITLE
Break notebooks out into functions for easier feedback

### ISSUE THREAD

**Issue by ljwolf** [jeffcsauer/GSOC2020#1]
It's harder for us to give feedback on the entire notebook. It'd be good if we could move the `losh` function (and, in the future, the join count stuff) to a module outside of the notebook.

**Comment by jeffcsauer** [comment]
Sounds good! Addressed in [commit b720cf1](https://github.com/jeffcsauer/GSOC2020/commit/b720cf1d882197e6fc639df92694e2fba693ffba).

**Comment by ljwolf** [comment]
Killer!
