### ISSUE TITLE
Row sums should use sparse weights

### ISSUE THREAD

**Issue by ljwolf** [jeffcsauer/GSOC2020#2]
When you're building [row sums for the weights matrix](https://gist.github.com/ljwolf/2da0a8f52bba6dd9fcfcf6faf97b24e7#file-losh-py-L84), I think it'd be better to use:
```python
row_sums = numpy.asarray(w.sparse.sum(axis=1)).flatten()
```
Since this does the summation within the sparse matrix code, rather than a list comprehension. Generally, we are trying to use the `w.sparse` for most operations on the weights matrix that can be expressed as a loop over each observation. 

Also, as a tip, you might want to use a different name than `y` when doing something like you're doing there... Just to avoid confusion, using an "iterator" index like `i` would work well:
```python
Wrs = [round(np.sum(list(w[i].values()))) for i in range(len(y))]
```
Also, just as a bit of information: it's not necessarily the case that `w` will have indexes `range(len(y))`. Sometimes, the indices will be strings, or numbers you don't know are sequential! This usually happens when you bulid a weights using something where the indices are like FIPS codes or unique identifiers: 

```python
import libpysal
import geopandas
df = geopandas.read_file(libpysal.examples.get_path('NAT.shp'))
w = libpysal.weights.Rook.from_dataframe(df, ids=df.FIPS.tolist())
```
So... we usually iterate over `w.id_order` if we need to extract keys by name rather than position.

**Comment by jeffcsauer** [comment]
Thanks so much for this! I had figured there must be a way to get rowsums out of a weights object that I was missing. Implementing this and will link the relevant pull.

Addressed in [commit b720cf1](https://github.com/jeffcsauer/GSOC2020/commit/b720cf1d882197e6fc639df92694e2fba693ffba).
