### ISSUE TITLE
Warn or raise (don't print), & be conservative about it

### ISSUE THREAD

**Issue by ljwolf** [jeffcsauer/GSOC2020#4]
When you [print](https://gist.github.com/ljwolf/2da0a8f52bba6dd9fcfcf6faf97b24e7#file-losh-py-L69) here, the intent is admirable: You don't want users to request `chi-squared` inference and `a=1`, since this would result in garbage. No matter what, use the `warnings` module in the standard library to raise warnings. Never print what should be a warning. 

And, currently, if the user passes something like `losh(inference="garbage")`, it's treated the same as `inference=None`, since there's no `else` in [the `if/elif` statement](https://gist.github.com/ljwolf/2da0a8f52bba6dd9fcfcf6faf97b24e7#file-losh-py-L68). 

So, be bold about it!
1. raise a warning if someone passes a nonsense inference method. 
2. warn (or raise) if someone sends `inference='chi-square'` and `a!=2`. 

This would look like:

```python
import warnings # somewhere up top 

...
if self.inference is None:
    return self
elif self.inference == 'chi-square':
    if a != 2:
        warnings.warn(f'Chi-square inference assumes that a=2, but a={a}. This means the inference will be invalid!')
        # OR
        # raise ValueError(f'Chi-square inference assumes that a=2, but a={a}. This means inference would be invalid. Use `a=2` to conduct inference using the chi-square approximation.')
else:
    raise NotImplementedError(f'The requested inference method ({self.inference}) is not currently supported!')
```
To support this, you might need to set `a=2` as the [default](https://gist.github.com/ljwolf/2da0a8f52bba6dd9fcfcf6faf97b24e7#file-losh-py-L42) in `fit`.

**Comment by jeffcsauer** [comment]
Thanks for the detailed info and example on using `warnings`! For example, feeding `garbage` as the inference method now raises: 

`NotImplementedError: The requested inference method (garbage) is not currently supported!`

Same goes for an `a` value not 2:

` <ipython-input-21-621572a1ef6d>:71: UserWarning: Chi-square inference assumes that a=2, but a=10. This means the inference will be invalid!`

This is really helpful and has been implemented in commit [46df0d1](https://github.com/jeffcsauer/GSOC2020/commit/46df0d10bf48a33b4c1d10653486f4041cbd7e59). I will be sure to use this structure going forward.
